/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as HousesRouteImport } from './routes/houses'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as SendRouteImport } from './routes/send'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatPeerRouteImport } from './routes/chat.$peer'
import { Route as HousesIdRouteImport } from './routes/houses_.$id'
import { Route as LaunchIdRouteImport } from './routes/launch_.$id'
import { Route as MarketsIdRouteImport } from './routes/markets_.$id'
import { Route as PayAddressRouteImport } from './routes/pay.$address'
import { Route as TokenAddressRouteImport } from './routes/token.$address'
import { Route as UNameRouteImport } from './routes/u.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const HousesRoute = HousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRoute,
} as any)
const ChatPeerRoute = ChatPeerRouteImport.update({
  id: '/$peer',
  path: '/$peer',
  getParentRoute: () => ChatRoute,
} as any)
const HousesIdRoute = HousesIdRouteImport.update({
  id: '/houses_/$id',
  path: '/houses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchIdRoute = LaunchIdRouteImport.update({
  id: '/launch_/$id',
  path: '/launch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIdRoute = MarketsIdRouteImport.update({
  id: '/markets_/$id',
  path: '/markets/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayAddressRoute = PayAddressRouteImport.update({
  id: '/pay/$address',
  path: '/pay/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenAddressRoute = TokenAddressRouteImport.update({
  id: '/token/$address',
  path: '/token/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const UNameRoute = UNameRouteImport.update({
  id: '/u/$name',
  path: '/u/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/chat': typeof ChatRouteWithChildren
  '/houses': typeof HousesRoute
  '/launch': typeof LaunchRoute
  '/markets': typeof MarketsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/swap': typeof SwapRoute
  '/wallet': typeof WalletRoute
  '/activity/$id': typeof ActivityIdRoute
  '/chat/$peer': typeof ChatPeerRoute
  '/houses/$id': typeof HousesIdRoute
  '/launch/$id': typeof LaunchIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/pay/$address': typeof PayAddressRoute
  '/token/$address': typeof TokenAddressRoute
  '/u/$name': typeof UNameRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/houses': typeof HousesRoute
  '/launch': typeof LaunchRoute
  '/markets': typeof MarketsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/swap': typeof SwapRoute
  '/wallet': typeof WalletRoute
  '/activity/$id': typeof ActivityIdRoute
  '/chat/$peer': typeof ChatPeerRoute
  '/houses/$id': typeof HousesIdRoute
  '/launch/$id': typeof LaunchIdRoute
  '/markets/$id': typeof MarketsIdRoute
  '/pay/$address': typeof PayAddressRoute
  '/token/$address': typeof TokenAddressRoute
  '/u/$name': typeof UNameRoute
  '/chat': typeof ChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bridge': typeof BridgeRoute
  '/chat': typeof ChatRouteWithChildren
  '/houses': typeof HousesRoute
  '/launch': typeof LaunchRoute
  '/markets': typeof MarketsRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/swap': typeof SwapRoute
  '/wallet': typeof WalletRoute
  '/activity/$id': typeof ActivityIdRoute
  '/chat/$peer': typeof ChatPeerRoute
  '/houses_/$id': typeof HousesIdRoute
  '/launch_/$id': typeof LaunchIdRoute
  '/markets_/$id': typeof MarketsIdRoute
  '/pay/$address': typeof PayAddressRoute
  '/token/$address': typeof TokenAddressRoute
  '/u/$name': typeof UNameRoute
  '/chat/': typeof ChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bridge'
    | '/chat'
    | '/houses'
    | '/launch'
    | '/markets'
    | '/send'
    | '/settings'
    | '/swap'
    | '/wallet'
    | '/activity/$id'
    | '/chat/$peer'
    | '/houses/$id'
    | '/launch/$id'
    | '/markets/$id'
    | '/pay/$address'
    | '/token/$address'
    | '/u/$name'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bridge'
    | '/houses'
    | '/launch'
    | '/markets'
    | '/send'
    | '/settings'
    | '/swap'
    | '/wallet'
    | '/activity/$id'
    | '/chat/$peer'
    | '/houses/$id'
    | '/launch/$id'
    | '/markets/$id'
    | '/pay/$address'
    | '/token/$address'
    | '/u/$name'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/bridge'
    | '/chat'
    | '/houses'
    | '/launch'
    | '/markets'
    | '/send'
    | '/settings'
    | '/swap'
    | '/wallet'
    | '/activity/$id'
    | '/chat/$peer'
    | '/houses_/$id'
    | '/launch_/$id'
    | '/markets_/$id'
    | '/pay/$address'
    | '/token/$address'
    | '/u/$name'
    | '/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BridgeRoute: typeof BridgeRoute
  ChatRoute: typeof ChatRouteWithChildren
  HousesRoute: typeof HousesRoute
  LaunchRoute: typeof LaunchRoute
  MarketsRoute: typeof MarketsRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  SwapRoute: typeof SwapRoute
  WalletRoute: typeof WalletRoute
  ActivityIdRoute: typeof ActivityIdRoute
  HousesIdRoute: typeof HousesIdRoute
  LaunchIdRoute: typeof LaunchIdRoute
  MarketsIdRoute: typeof MarketsIdRoute
  PayAddressRoute: typeof PayAddressRoute
  TokenAddressRoute: typeof TokenAddressRoute
  UNameRoute: typeof UNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/houses': {
      id: '/houses'
      path: '/houses'
      fullPath: '/houses'
      preLoaderRoute: typeof HousesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRoute
    }
    '/chat/$peer': {
      id: '/chat/$peer'
      path: '/$peer'
      fullPath: '/chat/$peer'
      preLoaderRoute: typeof ChatPeerRouteImport
      parentRoute: typeof ChatRoute
    }
    '/houses_/$id': {
      id: '/houses_/$id'
      path: '/houses/$id'
      fullPath: '/houses/$id'
      preLoaderRoute: typeof HousesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch_/$id': {
      id: '/launch_/$id'
      path: '/launch/$id'
      fullPath: '/launch/$id'
      preLoaderRoute: typeof LaunchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets_/$id': {
      id: '/markets_/$id'
      path: '/markets/$id'
      fullPath: '/markets/$id'
      preLoaderRoute: typeof MarketsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$address': {
      id: '/pay/$address'
      path: '/pay/$address'
      fullPath: '/pay/$address'
      preLoaderRoute: typeof PayAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token/$address': {
      id: '/token/$address'
      path: '/token/$address'
      fullPath: '/token/$address'
      preLoaderRoute: typeof TokenAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$name': {
      id: '/u/$name'
      path: '/u/$name'
      fullPath: '/u/$name'
      preLoaderRoute: typeof UNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ChatRouteChildren {
  ChatPeerRoute: typeof ChatPeerRoute
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatPeerRoute: ChatPeerRoute,
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BridgeRoute: BridgeRoute,
  ChatRoute: ChatRouteWithChildren,
  HousesRoute: HousesRoute,
  LaunchRoute: LaunchRoute,
  MarketsRoute: MarketsRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  SwapRoute: SwapRoute,
  WalletRoute: WalletRoute,
  ActivityIdRoute: ActivityIdRoute,
  HousesIdRoute: HousesIdRoute,
  LaunchIdRoute: LaunchIdRoute,
  MarketsIdRoute: MarketsIdRoute,
  PayAddressRoute: PayAddressRoute,
  TokenAddressRoute: TokenAddressRoute,
  UNameRoute: UNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
